import Link from 'next/link';
import { products } from '../data/products';

export default function Home(){
 const featured=products.filter(p=>p.featured);
 return <><header className="site-header"><div className="nav-wrap"><Link href="/" className="logo">AUTO<span>+</span></Link><nav><Link href="/products">Produits</Link><a href="#categories">Catégories</a><Link href="/about">À propos</Link></nav><Link href="/products" className="header-cta">Explorer <span>→</span></Link></div></header><main>
 <section className="hero"><div className="hero-copy"><div className="eyebrow">AUTO+ / ACCESSOIRES AUTOMOBILES</div><h1>Des accessoires qui donnent plus de confort à chaque trajet.</h1><p>Découvrez une sélection d’accessoires automobiles pratiques, esthétiques et pensés pour le quotidien.</p><Link className="primary" href="/products">Voir nos produits <span>→</span></Link></div><div className="hero-visual"><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-panel"><span>AUTO+</span><b>Drive.<br/>Upgrade.<br/>Enjoy.</b><i>Une sélection qui bouge avec vous.</i></div></div></section>
 <section className="feature-strip"><div><strong>Pratique</strong><span>Des accessoires choisis pour leur utilité.</span></div><div><strong>Soigné</strong><span>Une présentation simple et agréable.</span></div><div><strong>À découvrir</strong><span>Explorez les nouveautés Auto+.</span></div></section>
 <section className="section" id="selection"><div className="section-head"><div><div className="eyebrow">NOS SÉLECTIONS</div><h2>Les essentiels du moment</h2></div><Link href="/products" className="all-link">Voir tous les produits <span>→</span></Link></div><div className="product-grid">{featured.map(p=><article className="product-card" key={p.id}><Link href={`/product/${p.slug}`} className="product-image"><img src={p.image} alt={p.name}/><span>{p.offerLabel}</span></Link><div className="product-body"><h3>{p.name}</h3><p>{p.shortDescription}</p><div className="product-bottom"><Link className="offer-link" href={`/go/${p.slug}`}>Voir l’offre <span>→</span></Link></div></div></article>)}</div></section>
 <section className="categories" id="categories"><div className="section-head"><div><div className="eyebrow">EXPLORER</div><h2>Par catégorie</h2></div></div><div className="category-grid">{['Supports téléphone','Énergie','Organisation','Nettoyage','Confort','Éclairage'].map((c,i)=><Link className="category-card" key={c} href={`/products?category=${encodeURIComponent(c)}`}><span>0{i+1}</span><strong>{c}</strong><em>→</em></Link>)}</div></section>
 </main><footer><div className="footer-top"><div><Link href="/" className="logo">AUTO<span>+</span></Link><p>Des accessoires automobiles utiles à découvrir.</p></div><div className="footer-links"><Link href="/products">Produits</Link><Link href="/about">À propos</Link><Link href="/privacy">Confidentialité</Link><Link href="/legal">Mentions légales</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Auto+</span><span>Une sélection d’accessoires automobiles.</span></div></footer></>
}
